<?php

namespace AppBundle\Repository;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends \Doctrine\ORM\EntityRepository
{
    public function historyOfChallenge($exerciseId){

        $qb=$this->createQueryBuilder('o');
        return $qb
            ->where('o.exerciseId=:exerciseId')
            ->setParameter('exerciseId', $exerciseId)
            ->getQuery()
            ->getResult();
    }
}
