<?php

namespace AppBundle\Repository;

/**
 * RelationshipsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipsRepository extends \Doctrine\ORM\EntityRepository
{
}
