<?php

namespace AppBundle\Repository;

/**
 * RelationshipsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipsRepository extends \Doctrine\ORM\EntityRepository
{
    public function showFriends($userId){
            $qb=$this->createQueryBuilder('o');
            return $qb
                ->select('o.userOneId', 'o.userTwoId')
                ->where('o.userOneId=:userid or o.userTwoId=:userid and o.status=1')
                ->setParameter('userid', $userId)
                ->getQuery()
                ->getResult();
        }
}
